---
name: Rust Testing
"on":
  push:

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.8
        with:
          version: "v0.4.2"
      - name: Install required packages
        run: |
          sudo apt-get update && sudo apt-get -y install \
          libleptonica-dev \
          libtesseract-dev \
          clang
      - name: cargo build
        run: cargo build --verbose --release
      - name: cargo test
        run: cargo test --verbose
